version: '2'
services:
  backend:
    build: ./backend
    tty: true
    volumes:
      - ./backend/code:/code
    command: backend dev
    depends_on:
      - postgres
    networks:
      rotarran_net:

  frontend:
    build: ./frontend
    tty: true
    volumes:
      - ./frontend/code:/code
    command: npm run dev
    networks:
      rotarran_net:

  nginx:
    build: ./nginx
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/logs:/logs
    networks:
      rotarran_net:
        ipv4_address: 169.253.0.240

  postgres:
    image: postgres:9.4
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=rotarran
      - POSTGRES_USER=rotarran
      - POSTGRES_DB=rotarran
      - PGPASSWORD=rotarran
    networks:
      rotarran_net:

networks:
  rotarran_net:
    driver: bridge
    ipam:
     config:
       - subnet: 169.253.0.0/16
         gateway: 169.253.0.1
