version: '2'
services:
  backend:
    build: ./backend
    tty: true
    volumes:
      - ./backend/code:/code
    command: backend -t dev
    networks:
      kamar_net:

  frontend:
    build: ./frontend
    tty: true
    volumes:
      - ./frontend/code:/code
    command: npm run dev
    networks:
      kamar_net:

  nginx:
    build: ./nginx
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/logs:/logs
    networks:
      kamar_net:
        ipv4_address: 169.253.0.240

networks:
  kamar_net:
    driver: bridge
    ipam:
     config:
       - subnet: 169.253.0.0/16
         gateway: 169.253.0.1
