version: '2'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/code:/code
    command: pserve backend.ini --reload
    networks:
      kamar_net:

  nginx:
    build: ./nginx
    depends_on:
      - backend
    volumes:
      - ./nginx/logs:/logs
    networks:
      kamar_net:
        ipv4_address: 169.253.0.240

networks:
  kamar_net:
    driver: bridge
    ipam:
     config:
       - subnet: 169.253.0.0/16
         gateway: 169.253.0.1
